### PR TITLE
Add a basic deb build based on debian:jessie.

### PR DESCRIPTION
**Pull request by leocomitale**
Sorry for the delay.  This is a basic deb generator also using docker.  I left out the docker build target in the makefile as I figure you didn't want it anyway.

### CODE REVIEW

**Comment by alexpreynolds** [comment]
Hi Leo, 

If you have a second, can you please include a build target? That would help with testing and distribution.

Cheers,
Alex

**Comment by leocomitale** [comment]
OK, added it back.  Not sure what's going on with the ci build there.

**Comment by alexpreynolds** [comment]
Not sure what's up with the CI failures, either. I will investigate on this end when I can.

**Comment by alexpreynolds** [comment]
Added Debian target in commit 7de01f9e6d6da3d508e456bcc268ae3cfbddc53b

**Pull request closed without merging**
