### PR TITLE
use release tarballs for zlib, bzip and jansson

### PR DESCRIPTION
**Pull request by rekado**
This is a first proposed step to make it possible to build bedops with upstream releases of bzip2, zlib and jansson.

The bundled, patched tarballs have been replaced with upstream release tarballs for zlib, bzip and jansson.
After unpacking the tarballs, the library sources are then patched.  The patches have been derived from a diff between the bundled tarballs and upstream releases.

Note: this pull request is only for discussion purposes.  The Makefile for darwin has not been updated yet to deal with stock tarballs.  If this change looks acceptable, though, I could add a patch for `system.mk/Makefile.darwin`.

What do you think?

### CODE REVIEW

**Comment by alexpreynolds** [comment]
Thanks — I'll try to look at this soon.

**Comment by rekado** [comment]
Do you want me to rebase this patch to latest master?

**Comment by alexpreynolds** [comment]
If you'd like to base your patches of the current release, that would be
fine. Sorry for the long delay, but I'm working (slowly) on a rewrite of
the starch format that will use callback functions I'm working into bzip2
and gzip libraries. I may need to still hold off on incorporating your pull
request until I have a better idea how to ultimately bring in my code, when
it gets done.

**Comment by rekado** [comment]
> I'm working (slowly) on a rewrite of the starch format that will use callback functions I'm working into bzip2 and gzip libraries.

Does this mean that you are forking the bzip2 and gzip libraries?  Would it not be possible to place your enhancements into separate libraries rather than forking these very common libraries?

**Comment by rekado** [comment]
Hi again,

are you still planning to maintain a fork of the bzip2 and gzip libraries?  I very much recommend to keep the changes separate from these upstream libraries and write a wrapper if absolutely necessary.

Bundling libraries is troublesome enough --- bundling modified versions makes it virtually impossible for packagers to fix security bugs.

**Comment by rekado** [comment]
¯\_(ツ)_/¯

**Pull request closed without merging**
